# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from timer import TimerWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QToolButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(350, 310, 291, 51))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 60, 741, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Studium = QtWidgets.QLabel(self.frame)
        self.Studium.setGeometry(QtCore.QRect(60, 10, 611, 181))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.Studium.setFont(font)
        self.Studium.setObjectName("Studium")
        self.GoalButton = QtWidgets.QToolButton(self.centralwidget)
        self.GoalButton.setGeometry(QtCore.QRect(350, 390, 291, 51))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.GoalButton.setFont(font)
        self.GoalButton.setObjectName("GoalButton")
        self.InfoButton = QtWidgets.QToolButton(self.centralwidget)
        self.InfoButton.setGeometry(QtCore.QRect(350, 470, 291, 51))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.InfoButton.setFont(font)
        self.InfoButton.setObjectName("InfoButton")
        self.OptionButton = QtWidgets.QToolButton(self.centralwidget)
        self.OptionButton.setGeometry(QtCore.QRect(350, 550, 291, 51))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OptionButton.setFont(font)
        self.OptionButton.setObjectName("OptionButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.StartButton.clicked.connect(MainWindow.StartEvent)
        self.GoalButton.clicked.connect(MainWindow.GoalEvent)
        self.InfoButton.clicked.connect(MainWindow.InfoEvent)
        self.OptionButton.clicked.connect(MainWindow.OptionEvent)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def StartEvent(self):
        temp = TimerWindow()
        r = temp.showModal()

    def GoalEvent():
        pass

    def InfoEvent():
        pass

    def OptionEvent():
        pass


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "학습 시작하기"))
        self.Studium.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">STUDIUM</p></body></html>"))
        self.GoalButton.setText(_translate("MainWindow", "도전 과제"))
        self.InfoButton.setText(_translate("MainWindow", "내 정보"))
        self.OptionButton.setText(_translate("MainWindow", "설정"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
