# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TimerWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TimerLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.TimerLCD.setGeometry(QtCore.QRect(210, 110, 531, 211))
        self.TimerLCD.setObjectName("TimerLCD")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(210, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.RestartButton = QtWidgets.QPushButton(self.centralwidget)
        self.RestartButton.setGeometry(QtCore.QRect(390, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RestartButton.setFont(font)
        self.RestartButton.setObjectName("RestartButton")
        self.PauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PauseButton.setGeometry(QtCore.QRect(570, 360, 171, 41))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PauseButton.setFont(font)
        self.PauseButton.setObjectName("PauseButton")
        self.CurrentStateButton = QtWidgets.QToolButton(self.centralwidget)
        self.CurrentStateButton.setGeometry(QtCore.QRect(210, 430, 531, 91))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentStateButton.setFont(font)
        self.CurrentStateButton.setObjectName("CurrentStateButton")
        self.InfoButton = QtWidgets.QToolButton(self.centralwidget)
        self.InfoButton.setGeometry(QtCore.QRect(710, 590, 81, 31))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.InfoButton.setFont(font)
        self.InfoButton.setObjectName("InfoButton")
        self.OptionButton = QtWidgets.QToolButton(self.centralwidget)
        self.OptionButton.setGeometry(QtCore.QRect(810, 590, 81, 31))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.OptionButton.setFont(font)
        self.OptionButton.setObjectName("OptionButton")
        self.BackButton = QtWidgets.QToolButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(90, 590, 81, 31))
        font = QtGui.QFont()
        font.setFamily("IM혜민 Bold")
        font.setBold(True)
        font.setWeight(75)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "시작"))
        self.RestartButton.setText(_translate("MainWindow", "일시정지 / 재시작"))
        self.PauseButton.setText(_translate("MainWindow", "정지"))
        self.CurrentStateButton.setText(_translate("MainWindow", "현재 상태 / 미션 정보"))
        self.InfoButton.setText(_translate("MainWindow", "내 정보"))
        self.OptionButton.setText(_translate("MainWindow", "설정"))
        self.BackButton.setText(_translate("MainWindow", "뒤로 가기"))

    def showModal(self):
        return super().exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TimerWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
